In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.data_loader import load_all_data

data = load_all_data()

In [5]:
data.keys()

dict_keys(['customers_medium', 'menu_items', 'orders_medium', 'order_items (2)', 'restaurants'])

In [6]:
customers = data["customers_medium"]
menu_items = data["menu_items"]
order_items = data["order_items (2)"]
orders = data["orders_medium"]
restaurants = data["restaurants"]

In [7]:
print("Customers:", customers.shape)
print("Menu Items:", menu_items.shape)
print("Order Items:", order_items.shape)
print("Orders:", orders.shape)
print("Restaurants:", restaurants.shape)

Customers: (1500, 3)
Menu Items: (400, 3)
Order Items: (12391, 4)
Orders: (5000, 6)
Restaurants: (120, 4)

In [6]:
display(customers.head())
display(menu_items.head())
display(order_items.head())
display(orders.head())
display(restaurants.head())

  customer_id        city signup_date
0       C0001     Bristol  2022-04-25
1       C0002      London  2022-10-09
2       C0003  Manchester  2022-08-17
3       C0004  Manchester  2022-04-15
4       C0005     Bristol  2023-07-13

  item_id restaurant_id  price
0   M0001          R013  20.34
1   M0002          R090  20.84
2   M0003          R009  15.51
3   M0004          R104  29.88
4   M0005          R003  34.72

  order_id item_id  quantity  price
0   O00001   M0197         2   7.93
1   O00001   M0223         1  14.20
2   O00001   M0196         3  26.56
3   O00001   M0326         3   6.03
4   O00002   M0172         3  35.65

,order_id,customer_id,restaurant_id,order_time,delivery_time,status
0,O00001,C1234,R041,2023-01-17,2023-01-17 00:43:00,Late
1,O00002,C1017,R019,2023-04-24,2023-04-24 00:33:00,Cancelled
2,O00003,C0488,R045,2024-01-17,2024-01-17 00:29:00,Cancelled
3,O00004,C1452,R086,2023-03-27,2023-03-27 00:31:00,Late
4,O00005,C0915,R002,2024-01-09,2024-01-09 01:02:00,Cancelled

  restaurant_id   cuisine        city  rating
0          R001    Indian  Manchester     3.4
1          R002   Chinese       Leeds     4.1
2          R003   Chinese       Leeds     4.1
3          R004      Thai  Birmingham     3.5
4          R005  American     Bristol     4.3

In [7]:
datasets = {
    "Customers": customers,
    "Menu Items": menu_items,
    "Order Items": order_items,
    "Orders": orders,
    "Restaurants": restaurants
}

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.info())

Customers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1500 non-null   object
 1   city         1500 non-null   object
 2   signup_date  1500 non-null   object
dtypes: object(3)
memory usage: 35.3+ KB
None

Menu Items
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item_id        400 non-null    object
 1   restaurant_id  400 non-null    object
 2   price          400 non-null    float64
dtypes: float64(1), object(2)
memory usage: 9.5+ KB
None

Order Items
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12391 entries, 0 to 12390
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  12391 non-null  object
 1   item_id   12391 non-null  object
 2   quantity  12391 non-null  int64
 3   price     12391 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 387.3+ KB
None

Orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5000 non-null   object
 1   customer_id    5000 non-null   object
 2   restaurant_id  5000 non-null   object
 3   order_time     5000 non-null   object
 4   delivery_time  5000 non-null   object
 5   status         5000 non-null   object
dtypes: object(6)
memory usage: 234.5+ KB
None

Restaurants
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   restaurant_id  120 non-null    object
 1   cuisine        120 non-null    object
 2   city           120 non-null    object
 3   rating         120 non-null    float64
dtypes: float64(1), object(3)
memory usage: 3.9+ KB
None

In [9]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Customers
customer_id    0
city           0
signup_date    0
dtype: int64

Menu Items
item_id          0
restaurant_id    0
price            0
dtype: int64

Order Items
order_id    0
item_id     0
quantity    0
price       0
dtype: int64

Orders
order_id         0
customer_id      0
restaurant_id    0
order_time       0
delivery_time    0
status           0
dtype: int64

Restaurants
restaurant_id    0
cuisine          0
city             0
rating           0
dtype: int64

In [10]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

Customers: 0 duplicate rows
Menu Items: 0 duplicate rows
Order Items: 0 duplicate rows
Orders: 0 duplicate rows
Restaurants: 0 duplicate rows

In [11]:
customers.describe(include="all")

       customer_id     city signup_date
count         1500     1500        1500
unique        1500        6         619
top          C0001  Bristol  2023-04-10
freq             1      270           8

In [16]:
menu_items.describe()

            price
count  400.000000
mean    22.590175
std     10.123393
min      5.040000
25%     13.980000
50%     22.690000
75%     31.582500
max     40.000000

In [17]:
order_items.describe()

           quantity         price
count  12391.000000  12391.000000
mean       1.993302     22.738791
std        0.819676     10.139028
min        1.000000      5.040000
25%        1.000000     14.280000
50%        2.000000     22.880000
75%        3.000000     31.810000
max        3.000000     40.000000

In [18]:
orders.describe()

,order_id,customer_id,restaurant_id,order_time,delivery_time,status
count,5000,5000,5000,5000,5000,5000
unique,5000,1452,120,501,4676,3
top,O00001,C1065,R021,2023-10-22,2024-05-14 00:45:00,Delivered
freq,1,11,57,20,3,1717

In [19]:
restaurants.describe()

           rating
count  120.000000
mean     4.006667
std      0.595464
min      3.000000
25%      3.500000
50%      4.000000
75%      4.525000
max      5.000000